lint:
  rules:
    no_default: true

    add:
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - REPEATED_FIELD_NAMES_PLURALIZED
      - RPC_NAMES_UPPER_CAMEL_CASE
      - PACKAGE_NAME_LOWER_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - ENUM_NAMES_UPPER_CAMEL_CASE
